env:
  commonjs: true
  es6: true
  jest/globals: true
  node: true
extends:
  - eslint:recommended
  - plugin:jest/recommended
  - plugin:jest/style
  - plugin:prettier/recommended
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
plugins:
  - jest
  - prettier
rules:
  prettier/prettier: "error"
